// This file is auto generated by font.py
// Do not edit this file directly.
// Font: JF-Dot-Shinonome12.ttf
// Font Size: 12x12
// Code Set: TEST
// Character count: 2
// data size:36 bytes
struct KanjiData {
	uint32_t Unidoe;
	uint16_t SJIS;
	uint16_t JIS;
	uint8_t width;
	uint8_t height;
	uint32_t offsetBMP;
};
static const KanjiData JFDotShinonome12_12x12_TEST[] = {
	{ 0x00000041 , 0x0041 , 0x0041 ,  6 ,12 , 0x00000000 }},	// A
	{ 0x0000c2a8 , 0x814e , 0x212f , 12 ,12 , 0x0000000c }} 	// ¨
};
static const uint8_t JFDotShinonome12_12x12_TEST_bitmap[] = {
// UNICODE:0x00000041 -  Offset:0x00000000   -- CHAR:"A" 
	0x00,		// 00000000 
	0x20,		// 00100000 
	0x20,		// 00100000 
	0x50,		// 01010000 
	0x50,		// 01010000 
	0x50,		// 01010000 
	0xf8,		// 11111000 
	0x88,		// 10001000 
	0x88,		// 10001000 
	0x88,		// 10001000 
	0x00,		// 00000000 
	0x00,		// 00000000 

// UNICODE:0x0000c2a8 -  Offset:0x0000000c   -- CHAR:"¨" 
	0x19,	0x80,		// 0001100110000000 
	0x19,	0x80,		// 0001100110000000 
	0x00,	0x00,		// 0000000000000000 
	0x00,	0x00,		// 0000000000000000 
	0x00,	0x00,		// 0000000000000000 
	0x00,	0x00,		// 0000000000000000 
	0x00,	0x00,		// 0000000000000000 
	0x00,	0x00,		// 0000000000000000 
	0x00,	0x00,		// 0000000000000000 
	0x00,	0x00,		// 0000000000000000 
	0x00,	0x00,		// 0000000000000000 
	0x00,	0x00,		// 0000000000000000 

};
