// This file is auto generated by font.py
// Do not edit this file directly.
// Font: JF-Dot-Shinonome12.ttf
// Font Size: 12
// Code Set: ALL
struct KanjiData {
	uint32_t Unidoe;
	uint16_t SJIS;
	uint16_t JIS;
	uint8_t width;
	uint8_t height;
	uint32_t offsetBMP;
};
static const KanjiData JFDotShinonome12_12_ALL[] = {
	{ 0x00e4ba9c , 0x889f , 0x3021 , 12 ,12 , 0x00000000 }},	// 亜
	{ 0x00e59496 , 0x88a0 , 0x3022 , 12 ,12 , 0x00000018 }} 	// 唖
};
static const uint8_t JFDotShinonome12_12_ALL_bitmap[] = {
// UNICODE:0x00e4ba9c -  Offset:0x00000000   -- CHAR:"亜" 
	0x00,	0x00,		// 0000000000000000 
	0x7f,	0xe0,		// 0111111111100000 
	0x09,	0x00,		// 0000100100000000 
	0x09,	0x00,		// 0000100100000000 
	0x3f,	0xc0,		// 0011111111000000 
	0x29,	0x40,		// 0010100101000000 
	0x29,	0x40,		// 0010100101000000 
	0x29,	0x40,		// 0010100101000000 
	0x3f,	0xc0,		// 0011111111000000 
	0x09,	0x00,		// 0000100100000000 
	0x09,	0x00,		// 0000100100000000 
	0x7f,	0xe0,		// 0111111111100000 

// UNICODE:0x00e59496 -  Offset:0x00000018   -- CHAR:"唖" 
	0x00,	0x00,		// 0000000000000000 
	0x1f,	0xe0,		// 0001111111100000 
	0xe2,	0x80,		// 1110001010000000 
	0xa2,	0x80,		// 1010001010000000 
	0xaf,	0xe0,		// 1010111111100000 
	0xaa,	0xa0,		// 1010101010100000 
	0xaa,	0xa0,		// 1010101010100000 
	0xaa,	0xa0,		// 1010101010100000 
	0xaf,	0xe0,		// 1010111111100000 
	0xe2,	0x80,		// 1110001010000000 
	0x02,	0x80,		// 0000001010000000 
	0x1f,	0xe0,		// 0001111111100000 

};
